.*: Assembler messages:
.*: Error: illegal operand rd can not be x0 `c.addiw x0,10'
.*: Error: illegal operand rd can not be x0 `c.jr x0'
.*: Error: illegal operand rd can not be x0 `c.jalr x0'
.*: Error: illegal operand rd can not be x0 `c.lwsp x0,0\(sp\)'
.*: Error: illegal operand rd can not be x0 `c.ldsp x0,0\(sp\)'
.*: Error: illegal operand crs2 can not be x0 `c.mv x1,x0'
.*: Error: illegal operand crs2 can not be x0 `c.add x1,x0'
