.*: Assembler messages:
.*: Error: illegal operand for vsetvli immediate field, value must be 0...2047 `vsetvli a0,a1,2048'
.*: Error: illegal operand for vector immediate field, value must be 0...31 `vsll.vi v4,v8,32'
.*: Error: illegal operand for vector immediate field, value must be -16...15 `vadd.vi v4,v8,-17'
.*: Error: illegal operand for vector immediate field, value must be -16...15 `vadd.vi v4,v8,16'
.*: Error: illegal operand for vector immediate field, value must be -15...16 `vmslt.vi v4,v8,-16'
.*: Error: illegal operand for vector immediate field, value must be -15...16 `vmslt.vi v4,v8,17'
